//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCImageHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Ja_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Ja_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCImageHelper.Properties.Resources-Ja-jp", typeof(Resources_Ja_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigCancel {
            get {
                return ResourceManager.GetString("ConfigCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigFileFormat {
            get {
                return ResourceManager.GetString("ConfigFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Params に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigParams {
            get {
                return ResourceManager.GetString("ConfigParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigQuality {
            get {
                return ResourceManager.GetString("ConfigQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigReset {
            get {
                return ResourceManager.GetString("ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSave {
            get {
                return ResourceManager.GetString("ConfigSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSaveDest {
            get {
                return ResourceManager.GetString("ConfigSaveDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSaveFormat {
            get {
                return ResourceManager.GetString("ConfigSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSaveFormat_Trans {
            get {
                return ResourceManager.GetString("ConfigSaveFormat_Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSelectDir {
            get {
                return ResourceManager.GetString("ConfigSelectDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FFMpegDownloadMessage {
            get {
                return ResourceManager.GetString("FFMpegDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FFMpegDownloadTitle {
            get {
                return ResourceManager.GetString("FFMpegDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRC Image Helper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarExit {
            get {
                return ResourceManager.GetString("ToolbarExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarSettings {
            get {
                return ResourceManager.GetString("ToolbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run when computer starts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarToggleAutoStart {
            get {
                return ResourceManager.GetString("ToolbarToggleAutoStart", resourceCulture);
            }
        }
    }
}
